# Generated by Django 4.2.7 on 2023-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagapp', '0002_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
