# Generated by Django 4.2.7 on 2023-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_customuser_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
